export const DISPLAY_ALERT: string = "SHOW_ALERT";
export const CLEAR_ALERT: string = "CLEAR_ALERT";
export const TOGGLE_SIDEBAR: string = "TOGGLE_SIDEBAR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const REGISTER_USER_BEGIN: string = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS: string = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR: string = "REGISTER_USER_ERROR";

export const VERIFY_USER_BEGIN = "VERIFY_USER_BEGIN";
export const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS";
export const VERIFY_USER_ERROR = "VERIFY_USER_ERROR";

export const LOGIN_USER_BEGIN: string = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS: string = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR: string = "LOGIN_USER_ERROR";
export const LOGOUT_USER: string = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const FORGET_PASSWORD_BEGIN = "FORGET_PASSWORD_BEGIN";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR";

export const RESET_PASSWORD_BEGIN = "RESET_PASSWORD_BEGIN";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const SET_EDIT_JOB = "SET_EDIT_JOB";
export const DELETE_JOB = "DELETE_JOB";
export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";
